xaxs: "i"
yaxs: "i"
tcl: 0.3
mgp: [1.5, 0.3, 0.0]
lty: 1
lwd: 1
points:
  pch: 6
  col: "red"
lines: NULL
abline:
  col: "grey"
legend: 
  title: "EXPLANATION"
  location: "topright"
axis:
  at: NULL
  labels: TRUE
  tick: TRUE 
  line: NULL 
  pos: NULL
  outer: FALSE
title: NULL
text: NULL
mtext: NULL
grid:
  col: "grey"
  lwd: 1
  lty: 2
segments: NULL
error_bar: NULL
arrows: NULL
callouts:
  col: 'black'
bgCol: NULL
orderToPlot:
  order: [grid, bgCol]
