xaxs: "i"
yaxs: "i"
tcl: 0.3
mgp: [1.5, 0.3, 0.0]
yaxt: "s"
xaxt: "s"
ann: TRUE
points:
  pch: 6
  col: "red"
lines: 
  col: "black"
  lty: 1
  lwd: 1
abline:
  col: "grey"
  lty: 1
  lwd: 1
axis:
  at: NULL
  labels: TRUE
  tick: TRUE 
  line: NULL 
  pos: NULL
  outer: FALSE
  las: 1
title: NULL
text: NULL
mtext: 
  las: 0
grid:
  col: "grey"
  lwd: 1
  lty: 2
segments: NULL
error_bar:
  y.high: 0 
  y.low: 0 
  x.high: 0
  x.low: 0
  epsilon: 0.1
arrows: NULL
callouts:
  col: 'black'
bgCol: 
  col: 'lightgrey'

